name: Prodeus
game_slug: prodeus
version: Good Old Games Installer
slug: prodeus
runner: wine

script:
  game:
    exe: $GAMEDIR/drive_c/GOG Games/Prodeus/Prodeus.exe
    prefix: $GAMEDIR

  files:
    - setup: N/A:Select installer

  installer:
    - task:
        name: create_prefix
        install_mono: false
        install_gecko: false
        prefix: $GAMEDIR

    - task:
        executable: $setup
        name: wineexec
        prefix: $GAMEDIR

