name: Train Valley
game_slug: train-valley
version: Good Old Games
slug: train-valley
runner: wine
year: 2015

script:
  game:
    exe: $GAMEDIR/drive_c/GOG Games/Train Valley/Launch Train Valley.lnk
    prefix: $GAMEDIR

  files:
    - setup: N/A:Select installer
    - DLC1: N/A:Select DLC1 installer

  installer:
    - task:
        name: create_prefix
        install_mono: false
        install_gecko: false
        prefix: $GAMEDIR

    - task:
        executable: $setup
        name: wineexec
        prefix: $GAMEDIR

    - task:
        executable: $DLC1
        name: wineexec
        args: /SILENT 
        prefix: $GAMEDIR
